name: CI & Déploiement sur Render

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Vérification du code
      uses: actions/checkout@v3

    - name: Configuration de Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installation des dépendances
      run: npm ci

    - name: Exécution des tests
      run: npm test

    - name: Déclenchement du déploiement sur Render
      if: success()
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
